// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgIM7sCSzxgBpIiBk0KGGktwDyvj4gDrs',
    appId: '1:1039924036817:web:1dc08255feb5bd3a90b1f0',
    messagingSenderId: '1039924036817',
    projectId: 'my-shopify-01',
    authDomain: 'my-shopify-01.firebaseapp.com',
    storageBucket: 'my-shopify-01.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDj1G-WQOp0XFuyFdvimKLWL2WAi67JXZk',
    appId: '1:1039924036817:android:0f666914db50cb8890b1f0',
    messagingSenderId: '1039924036817',
    projectId: 'my-shopify-01',
    storageBucket: 'my-shopify-01.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjU1g9EsaHYktN9uNroxAuBN6cFD-rfB4',
    appId: '1:1039924036817:ios:10a9512ff6d1de1e90b1f0',
    messagingSenderId: '1039924036817',
    projectId: 'my-shopify-01',
    storageBucket: 'my-shopify-01.firebasestorage.app',
    iosBundleId: 'com.example.shopify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjU1g9EsaHYktN9uNroxAuBN6cFD-rfB4',
    appId: '1:1039924036817:ios:10a9512ff6d1de1e90b1f0',
    messagingSenderId: '1039924036817',
    projectId: 'my-shopify-01',
    storageBucket: 'my-shopify-01.firebasestorage.app',
    iosBundleId: 'com.example.shopify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCgIM7sCSzxgBpIiBk0KGGktwDyvj4gDrs',
    appId: '1:1039924036817:web:c8e7349301fa92d490b1f0',
    messagingSenderId: '1039924036817',
    projectId: 'my-shopify-01',
    authDomain: 'my-shopify-01.firebaseapp.com',
    storageBucket: 'my-shopify-01.firebasestorage.app',
  );
}
