name: Flutter CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test-android:
    runs-on: ubuntu-latest
    steps:
      # Checkout code
      - uses: actions/checkout@v4

      # Setup Flutter
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.35.2" # chỉnh version Flutter bạn dùng

      # Cài dependencies
      - run: flutter pub get

      # Kiểm tra format
      - run: dart format .

      # Static analyze
      - run: flutter analyze

      # Run test
      - run: flutter test

      # Build APK (debug/release tuỳ chọn)
      - run: flutter build apk --debug

      # Upload artifact (APK) để tải về
      - uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: build/app/outputs/flutter-apk/app-debug.apk

  build-test-ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.35.2"
      - run: flutter pub get
      - run: flutter analyze
      - run: flutter test
      - run: flutter build ios --no-codesign
